version: '3.8'

services:
  angular-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - dotnet-api

  dotnet-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api:/src  # Synchronizowanie kodu źródłowego z hosta
      - /root/.nuget/packages
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=TwojaBazaDanych;Username=postgres;Password=TwojeHaslo123;
    networks:
      - app-network
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "TwojeHaslo123"
      POSTGRES_DB: "TwojaBazaDanych"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
